{
    "url": "https://docs.snowflake.com/en/developer-guide/snowflake-python-api/reference/latest/_autosummary/snowflake.core.exceptions.ConflictError",
    "title": "snowflake.core.exceptions.ConflictError | Snowflake Documentation",
    "paragraphs": [
        "Bases: APIError",
        "Raised when we encounter an HTTP error code of 409.",
        "Was this page helpful?"
    ]
}